language: ruby
rvm:
- 2.5.0
before_install: gem update --remote bundler
install:
- bundle install --retry=3
script:
- bundle exec rspec
- bundle exec rubocop --config .rubocop.yml
- bundle exec codeclimate-test-reporter
deploy:
  provider: heroku
  api_key:
    secure: E/ujGyxd5NACrIF0ZBaIKmuRfpLq1ngpdZRtYcgeQyUDQffwlCjq8wGgvMgVfXQb8Pol1XhSikBaIpqrTBBKY9UT+1ITlbj8N7A2AY+i5bu+/CEmrfuRX2qjw8LqtS2hHbCIQ7T1ORGplC3d7Q3gu7OGyUTY4BnL2J0ZUUYk7op108pRQl659G0iOWrqz9VxOtizpq15Pm0wFr4kxDTpsDlOOv4Opsg1X0pDqoE3Oqu1UYYRd6F3J4OvtVgxKe9zTpZdH+U6zrUVVv38F/56590ZaVPbEHgFCT6LxKImDCVLX/JYn0cVKKUpl4nsKxuko08PvTHacIP4d73AvGGt832IMVknttznkzzQvbj7z+ewVH1TlzPy5/jF76YyHXmmggf7Ng9t3p2ZiftrSl6cBkU9yI0zidpJwAg2pwLn9ZvQp52zus258ithZYS8ydc221iRKPc/bohfkRkVNC0wIq6Lsl/lg6PKiHoAyVxrNwQsqqoyXYpSkIR/CNtfE5jyl59xyZP/xhkeJk7CJKMtqZSQGk9b3CWKjlrFZtj8ABMURwOuOpIP588LSQ2X1EN8h/1DpPmaHfQsYfhkbHq+WVdt9AnwPMaM8R37lOyr6+OOlccNPGeivcUqaK9r6SjbWl9wx1tok4VIY5Ifo/3XfHCODF54ekS52HAwUBubjMs=
  app:
    production: sharemeow
    master: sharemeow-staging
  on:
    repo: producthunt/ShareMeow
